train: "/media/roovedot/common/Pr.Inv.JavierFernandez/Image_Segmentation/dataYolo11Structure/train"
val: "/media/roovedot/common/Pr.Inv.JavierFernandez/Image_Segmentation/dataYolo11Structure/valid"

nc: 21
names: ['rectification border', 'ground', 'road', 'sidewalk', 'parking', 'rail track', 'wall', 'fence', 'guard rail', 'traffic light', 'terrain', 'person', 'rider', 'car', 'truck', 'bus', 'caravan', 'trailer', 'train', 'motorcycle', 'bicycle']
